CREATE DATABASE DuAn
GO
USE DuAn
GO

CREATE TABLE Roles
(
	RoleID INT NOT NULL PRIMARY KEY,
	RoleName NVARCHAR(20) NOT NULL,
	_Description NVARCHAR(100)
)

GO

CREATE TABLE Users
(
	UserID INT NOT NULL PRIMARY KEY,
	NickName NVARCHAR(20),
	UserName NVARCHAR(20) NOT NULL,
	PhoneNumber NVARCHAR(15),
	UserAddress NVARCHAR(100),
	EmailAddress NVARCHAR(20),
	Photo NVARCHAR(20),
	RoleID INT FOREIGN KEY REFERENCES Roles(RoleID)
)

GO

CREATE TABLE Account
(
	AccountID INT NOT NULL PRIMARY KEY,
	UserName NVARCHAR(20) NOT NULL,
	Passwords NVARCHAR(20) NOT NULL,
	UserID INT FOREIGN KEY REFERENCES Users(UserID)
)

GO

CREATE TABLE Area
(
	AreaID INT NOT NULL PRIMARY KEY,
	AreaName NVARCHAR(20) NOT NULL,
	_Description NVARCHAR(100)
)

GO 

CREATE TABLE _Service
(
	ServiceID INT NOT NULL PRIMARY KEY,
	TypeOfService NVARCHAR(20) NOT NULL,
	_Description NVARCHAR(100)
)

GO

CREATE TABLE Blog
(
	BlogID INT NOT NULL PRIMARY KEY,
	BlogName NVARCHAR(20) NOT NULL,
	Content NVARCHAR(100),
	Title NVARCHAR(20),
	Likes INT,
	_Status NVARCHAR(100),
	Photo NVARCHAR(20),
	Video NVARCHAR(20),
	UserID INT FOREIGN KEY REFERENCES Users(UserID)
)

GO

CREATE TABLE Comment
(
	CommentID INT NOT NULL PRIMARY KEY,
	CommentParentID INT NOT NULL,
	Content NVARCHAR(100),
	Title NVARCHAR(20),
	UserName NVARCHAR(20) NOT NULL,
	UserID INT FOREIGN KEY REFERENCES Users(UserID),
	AreaID INT FOREIGN KEY REFERENCES Area(AreaID),
	ServiceID INT FOREIGN KEY REFERENCES _Service(ServiceID)
)

GO

CREATE TABLE ThingsToDo
(
	ThingsToDoID INT NOT NULL PRIMARY KEY,
	TTDName NVARCHAR(20) NOT NULL,
	TTDAddress NVARCHAR(100),
	Price INT,
	Times DATETIME,
	Photo NVARCHAR(20),
	Video NVARCHAR(20),
	Rate INT,
	Comment NVARCHAR(100),
	_Description NVARCHAR(100),
	ServiceName NVARCHAR(20) NOT NULL,
	AreaID INT FOREIGN KEY REFERENCES Area(AreaID)
)

GO

CREATE TABLE Rate
(
	RateID INT NOT NULL PRIMARY KEY,
	ServiceName NVARCHAR(20) NOT NULL,
	UserID INT FOREIGN KEY REFERENCES Users(UserID),
	AreaID INT FOREIGN KEY REFERENCES Area(AreaID),
	ServiceID INT FOREIGN KEY REFERENCES _Service(ServiceID)
)

GO

CREATE TABLE EatAndDrink
(
	EatAndDrinkID INT NOT NULL PRIMARY KEY,
	EADName NVARCHAR(20) NOT NULL,
	EADAdress NVARCHAR(100),
	MenuTable NVARCHAR(20),
	ExteriorPhoto NVARCHAR(20),
	MenuPhoto NVARCHAR(20),
	Rate INT,
	Comment NVARCHAR(100),
	Detail NVARCHAR(100),
	ServiceName NVARCHAR(20) NOT NULL,
	AreaID INT FOREIGN KEY REFERENCES Area(AreaID)
)

GO

CREATE TABLE Stay
(
	StayID INT NOT NULL PRIMARY KEY,
	StayName NVARCHAR(20) NOT NULL,
	StayAddress NVARCHAR(100),
	Price INT,
	ExteriorPhoto NVARCHAR(20),
	Rate INT,
	Comment NVARCHAR(100),
	_Description NVARCHAR(100),
	AreaID INT FOREIGN KEY REFERENCES Area(AreaID)
)